Контрольная работа 2

In [1]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.linear_model import Perceptron
import time
from sklearn.datasets import fetch_openml

1. (1 балл) Загрузите предложенный вам датасет с помощью функции `sklearn.datasets.fetch_openml`. Выведите текстовое описание загруженного датасета. Обозначьте целевую переменную за `y`, а остальные данные за `X`.


In [14]:
from sklearn.datasets import fetch_openml
dataset = fetch_openml('diggle_table_a2', version=1)
print(dataset.DESCR)

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


**Author**:   
**Source**: Unknown - Date unknown  
**Please cite**:   

DATA-SETS FROM DIGGLE, P.J. (1990). TIME SERIES : A BIOSTATISTICAL
INTRODUCTION. Oxford University Press.

Table: Table A2 Wool prices


Information about the dataset
CLASSTYPE: numeric
CLASSINDEX: none specific

Downloaded from openml.org.


In [15]:
Y = dataset.target
X = dataset.data
Y

0      76
1      76
2      76
3      76
4      76
       ..
305    84
306    84
307    84
308    84
309    84
Name: col_1, Length: 310, dtype: category
Categories (9, object): ['76', '77', '78', '79', ..., '81', '82', '83', '84']

In [16]:
X

col_2  col_3  col_4  col_5   col_6   col_7   col_8   col_9
0       33     33  262.0  307.0  1.1718  5.5683  5.7268  0.1585
1       34     34  259.0  306.0  1.1815  5.5568  5.7236  0.1668
2       35     35  257.0  306.0  1.1907  5.5491  5.7236  0.1745
3       36     36  262.0  306.0  1.1679  5.5683  5.7236  0.1553
4       37     37  264.0  306.0  1.1591  5.5759  5.7236  0.1477
..     ...    ...    ...    ...     ...     ...     ...     ...
305     20    436  495.0  786.0  1.5879  6.2046  6.6670  0.4624
306     21    437  495.0  786.0  1.5879  6.2046  6.6670  0.4624
307     22    438  497.0  786.0  1.5815  6.2086  6.6670  0.4584
308     25    441  496.0  786.0  1.5847  6.2066  6.6670  0.4604
309     26    442  499.0  786.0  1.5752  6.2126  6.6670  0.4544

[310 rows x 8 columns]

2. (1 балл) Выведите основную статистическую информацию о данных. Сделайте количественное описание датасета: число строк (объектов), число столбцов (признаков), статистику по признакам, количество классов (значений целевой переменной).

In [17]:
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)
df['Target'] = Y
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   col_2   310 non-null    int64   
 1   col_3   310 non-null    int64   
 2   col_4   310 non-null    float64 
 3   col_5   310 non-null    float64 
 4   col_6   310 non-null    float64 
 5   col_7   310 non-null    float64 
 6   col_8   310 non-null    float64 
 7   col_9   310 non-null    float64 
 8   Target  310 non-null    category
dtypes: category(1), float64(6), int64(2)
memory usage: 20.2 KB


Выводим основную информацию по датасету, обращаем внимание на то, что

In [18]:
df.describe()

col_2       col_3       col_4       col_5       col_6       col_7  \
count  310.000000  310.000000  310.000000  310.000000  310.000000  310.000000   
mean    26.587097  234.922581  387.183871  496.103226    1.265265    5.943422   
std     15.335635  120.804559   66.762306  124.330267    0.116450    0.178233   
min      2.000000   33.000000  257.000000  306.000000    1.077800    5.549100   
25%     12.000000  127.250000  316.000000  357.000000    1.155950    5.755700   
50%     25.000000  233.500000  405.000000  524.000000    1.272000    6.003900   
75%     41.000000  338.750000  434.500000  576.000000    1.323075    6.074150   
max     51.000000  442.000000  499.000000  791.000000    1.604500    6.212600   

           col_8       col_9  
count  310.00000  310.000000  
mean     6.17463    0.231207  
std      0.25636    0.089691  
min      5.72360    0.075000  
25%      5.87770    0.144925  
50%      6.26150    0.240550  
75%      6.35610    0.280025  
max      6.67330    0.472800

Выводим статистику по признакам

In [19]:
Y.value_counts()

col_1
77    41
79    40
82    40
78    39
83    39
81    38
80    35
84    20
76    18
Name: count, dtype: int64

Выводим количество уникальных значений (классов) целевой переменной

3. (1 балл) Убедитесь, что данные пригодны для моделирования. В данных не должно быть пропущенных значений, ве признаки должны быть численными. Если эти условия нарушаются, исправьте это.


In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   col_2   310 non-null    int64   
 1   col_3   310 non-null    int64   
 2   col_4   310 non-null    float64 
 3   col_5   310 non-null    float64 
 4   col_6   310 non-null    float64 
 5   col_7   310 non-null    float64 
 6   col_8   310 non-null    float64 
 7   col_9   310 non-null    float64 
 8   Target  310 non-null    category
dtypes: category(1), float64(6), int64(2)
memory usage: 20.2 KB


В столбцах отсутствуют нулевые значения, все признаки имеют численный тип

4. (2 балла) Обучите модель логистической регрессии на рассматриваемых данных из библиотеки `sklearn`. Рассчитайте метрики accuracy и выведите таблицу классификации.


In [21]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [23]:
#Разделяем на тестовую и контрольную выборку
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1)


In [24]:
#Обучаем модель
model_log = LogisticRegression()
model_log.fit(X_train, Y_train)
Y_pred = model_log.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [25]:
print('accuracy = ', round(accuracy_score(Y_test, Y_pred), 4))

accuracy =  0.9677


In [26]:
confusion_matrix(Y_test, Y_pred)

array([[ 8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  8,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 12,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 12,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 11,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  1, 13,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 11,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  6,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1,  9]])

5. (2 балла) Обучите полиномиальную модель классификации. Рассчитайте метрики accuracy и выведите таблицу классификации. Попробуйте разные степени полинома и выберите ту, которая работает лучше.


In [27]:
from sklearn.preprocessing import PolynomialFeatures

In [31]:
powers = np.arange(2,11, 2)
for power in powers:
    model = PolynomialFeatures(power)
    X_train_model = model.fit_transform(X_train)
    X_test_model = model.transform(X_test)

    scaler = StandardScaler()
    X_train_model_scaled = scaler.fit_transform(X_train_model)
    X_test_model_scaled = scaler.transform(X_test_model)

    model_log = LogisticRegression(max_iter=25000)
    model_log.fit(X_train_model_scaled, Y_train)

    Y_pred = pd.Series(model_log.predict(X_test_model))

    print(f'Степень: {int(power)} | accuracy_score: {int(accuracy_score(Y_test, Y_pred))} | confusion_matrix:\n')
    print(confusion_matrix(Y_test, Y_pred), end='\n'*2+'-'*75+'\n')

Степень: 2 | accuracy_score: 0 | confusion_matrix:

[[ 0  0  0  0  0  0  0  0  8]
 [ 0  0  0  0  0  0  0  3  5]
 [ 0  0  0  0  0  0  0 11  1]
 [ 0  0  0  0  0  0  0 12  0]
 [ 0  0  0  0  0  0  0 12  0]
 [ 0  0  0  0  0  0  0 14  0]
 [ 0  0  0  0  0  0  0 11  0]
 [ 0  0  0  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  0 10  0]]

---------------------------------------------------------------------------
Степень: 4 | accuracy_score: 0 | confusion_matrix:

[[ 0  0  0  0  0  0  0  0  8]
 [ 0  0  0  0  0  0  0  0  8]
 [ 0  0  0  0  0  0  0  0 12]
 [ 0  0  0  0  0  0  0  0 12]
 [ 0  0  0  0  0  0  0  0 12]
 [ 0  0  0  0  0  0  0  0 14]
 [ 0  0  0  0  0  0  0  0 11]
 [ 0  0  0  0  0  0  0  0  6]
 [ 0  0  0  0  0  0  0  0 10]]

---------------------------------------------------------------------------
Степень: 6 | accuracy_score: 0 | confusion_matrix:

[[ 0  0  0  0  0  0  0  0  8]
 [ 0  0  0  0  0  0  0  0  8]
 [ 0  0  0  0  0  0  0  0 12]
 [ 0  0  0  0  0  0  0  0 12]
 [ 0  0  0  0  0  0  0  0 12

6. (2 балла) Обучите модель классификации по методу опорных векторов. Рассчитайте метрики accuracy и выведите таблицу классификации. Попробуйте разные ядерные функции и выберите ту, которая работает лучше.


In [32]:
from sklearn.svm import SVC

In [33]:
kernels = ['linear', 'poly', 'sigmoid']

In [34]:
for kernel in kernels:
    model_svm = SVC(kernel=kernel)

    model_svm.fit(X_train, Y_train)
    Y_pred = pd.Series(model_svm.predict(X_test))

    accuracy = accuracy_score(Y_test, Y_pred)

    print(f'Ядро: {kernel}, accuracy_score: {accuracy:.4f}\n')
    print(confusion_matrix(Y_test, Y_pred), end='\n'*2+'-'*75+'\n')

Ядро: linear, accuracy_score: 1.0000

[[ 8  0  0  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0]
 [ 0  0  0 12  0  0  0  0  0]
 [ 0  0  0  0 12  0  0  0  0]
 [ 0  0  0  0  0 14  0  0  0]
 [ 0  0  0  0  0  0 11  0  0]
 [ 0  0  0  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  0  0 10]]

---------------------------------------------------------------------------
Ядро: poly, accuracy_score: 0.6882

[[ 0  8  0  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0]
 [ 0  2  0 10  0  0  0  0  0]
 [ 0  0  0  2 10  0  0  0  0]
 [ 0  0  0  0  0 14  0  0  0]
 [ 0  0  0  0  0  2  9  0  0]
 [ 0  0  0  0  0  0  2  4  0]
 [ 0  0  0  0  0  0  0  1  9]]

---------------------------------------------------------------------------
Ядро: sigmoid, accuracy_score: 0.0000

[[ 0  0  0  0  0  0  0  8  0]
 [ 0  0  0  0  0  0  0  8  0]
 [ 0  0  0  0  0  0  0 12  0]
 [ 0  2  0  0  0  0  0 10  0]
 [ 0 12  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0]
 [ 0 11  0 

In [35]:
len(Y_test), len(Y_pred)

(93, 93)

7. (1 балл) Обучите модель классификации Перцептрон. Рассчитайте метрики accuracy и выведите таблицу классификации.


In [36]:
from sklearn.linear_model import Perceptron

In [37]:
# Создание и обучение модели перцептрона
perceptron_model = Perceptron(random_state=42)
perceptron_model.fit(X_train, Y_train)

# Предсказание на тестовой выборке
Y_perceptron_pred = perceptron_model.predict(X_test)

# Оценка модели
perceptron_accuracy = pd.Series(accuracy_score(Y_test, Y_perceptron_pred))
perceptron_conf_matrix = confusion_matrix(Y_test, Y_perceptron_pred)
perceptron_classification_rep = classification_report(Y_test, Y_perceptron_pred)


print(f'Accuracy: {perceptron_accuracy}\n')
print(f'Confusion Matrix:\n{perceptron_conf_matrix}\n')
print(f'Classification Report:\n{perceptron_classification_rep}\n')


Accuracy: 0    0.225806
dtype: float64

Confusion Matrix:
[[ 0  8  0  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 12]
 [ 0  0  0  0  0  0  1  0 13]
 [ 0  0  0  0  0  0  0  7  4]
 [ 0  0  0  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  0  3  7]]

Classification Report:
              precision    recall  f1-score   support

          76       0.00      0.00      0.00         8
          77       0.20      1.00      0.33         8
          78       0.00      0.00      0.00        12
          79       0.00      0.00      0.00        12
          80       0.00      0.00      0.00        12
          81       0.00      0.00      0.00        14
          82       0.00      0.00      0.00        11
          83       0.38      1.00      0.55         6
          84       0.19      0.70      0.30        10

    accuracy                           0.23        93
   macro avg       0.09      0.30      0.13        

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
